on:
  workflow_dispatch:
  schedule:
    - cron: "22 * * * *"

jobs:
  getActive:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      # Download current active hashflags
      - run: ./scripts/getCurrent.sh
      # Append new data to the json files
      - run: go run main.go
      # Download hashflag images
      - run: ./scripts/getAssets.sh
      # Commit new files
      - run: ./scripts/commit.sh
