on:
  workflow_dispatch:
  schedule:
    - cron: "22 * * * *"

jobs:
  getActive:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.19"

      - name: Download current active hashflags
        run: ./scripts/getCurrent.sh

      - name: Append new data to the json files
        run: go run main.go

      - name: Download hashflag images
        run: ./scripts/getAssets.sh

      - name: Commit New files
        run: ./scripts/commit.sh
