on:
  workflow_dispatch:
  schedule:
    - cron: "22 * * * *"

jobs:
  getActive:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - run: go run hello.go

      - run: ./scripts/getCurrent.sh
      - run: go run main.go
      - run: ./scripts/getAssets.sh
      - run: ./scripts/commit.sh
