on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "42 * * * *"

jobs:
  getActive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x      
      
      - name: Fetch & Process Data
        run: deno run --allow-net --allow-read --allow-write main.ts

      - name: Download assests
        run: ./scripts/download.sh

      - name: Commit New files
        run: ./scripts/commit.sh
